### ISSUE TITLE
could wgEncodeCrgMapabilityAlign100mer.bw used for PE150 ?

### ISSUE THREAD

**Issue by ChenFengling** [ay-lab/HiCnv#3]
Hello ,
I'm using this script for CNV calling. I wonder when I'm creating *.F_GC_MAP.bed could I use wgEncodeCrgMapabilityAlign100mer.bw used for PE150 sequenced data. If not, what should I do?

**Comment by abhijitcbio** [comment]
Yes, you can use the 100mer file.

Please change the variables of the "HiCnv/scripts/F_GC_MAP_Files/create_F_GC_MAP_file.pl" script inorder to generate the file.

After you download the  wgEncodeCrgMapabilityAlign100mer.bw file, please convert the file into bedgraph format using the following command

bigWigToBedGraph wgEncodeCrgMapabilityAlign100mer.bw MapabilityAlign100mer.bedGraph

You also need the genome sequence file. To download the file you can use the following script 

perl -e '@chr=qw(chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM); $i=0;while($i<=$#chr){chomp $chr[$i]; system("curl http://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/$chr[$i].fa.gz|zcat > hg19.$chr[$i].fa"); $i++;} system("cat hg19.*.fa > hg19.fa");' 

(You can change hg19 to hg18 to download hg18 genome sequence file)
