### ISSUE TITLE
How to set $ref_chrom  in running? 

### ISSUE THREAD

**Issue by liufuyan2016** [ay-lab/HiCnv#5]
How to set $ref_chrom  in running? Thnnk you!

$ref_chrom   = "chr2";  #Reference chromosome to calculate PIC and labelling the CNVs. 
 17 #This is a critical choise, please refer PMID 29048467, for reference choice

**Comment by abhijitcbio** [comment]
A simple option is to plot the one-dimensional raw coverage of each bin (say @50Kb resolution) to select the normal chromosome. For example, see the below figure

![image](https://user-images.githubusercontent.com/36205296/49046159-0d8d2400-f188-11e8-9d7c-e87d12da7d8f.png)

Here, chr2 and chr4 shows a more smoother coverage profile then others, so chr2 or chr4 can be used as a reference chromosome. Also, please be careful from whole genome duplication or deletion cases. In those situations the coverage profile may look smoother and should be compared to other chromosome coverages before deciding upon the reference chromosome.
