### ISSUE TITLE
Only get 38 CNV regions ?

### ISSUE THREAD

**Issue by liufuyan2016** [ay-lab/HiCnv#6]
I call CNV region use Tumour sample ,but only 38 regions I get. Do you think the number is small?

**Comment by abhijitcbio** [comment]
It depends on the tumor type, if the sample has an overall small CNV regions then its possible. Try to check the figures like the following 

![image](https://user-images.githubusercontent.com/36205296/49331272-47c34080-f54f-11e8-8e35-b023973674b9.png)

If the segments in your figures makes sense then yes, if not try to set another reference chromosome.
