### ISSUE TITLE
Error running HiCnv

### ISSUE THREAD

**Issue by jstansfield0** [ay-lab/HiCnv#7]
I'm trying to run HiCnv on a dataset and I got this error when running the HiCnv.sh script:

```
Error in model.frame.default(formula = count ~ len_vec + gcc_vec + map_vec,  : 
  invalid type (NULL) for variable 'count'
Calls: glm -> eval -> eval -> <Anonymous> -> model.frame.default
Execution halted
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'WM2664.F_GC_MAP.NormCount.0.2_0.5_1000.bed': No such file or directory
Execution halted
```

Do you know what would be causing the issue here?

**Comment by abhijitcbio** [comment]
It says "WM2664.F_GC_MAP.NormCount.0.2_0.5_1000.bed" file is missing. This file should have the following fields
<chr>  <start> <end> <gc> <map> <frag> <count> <norm.count>

and should be generated by running the following command

Rscript ../scripts/normalize.r WM2664 0.2 0.5 550

Do you see the file in the same folder?

**Comment by jstansfield0** [comment]
I don't see the WM2664 0.2 0.5 550 file anywhere in the folders.

**Comment by abhijitcbio** [comment]
Have you followed the step 1 and generated perREfragStats and F_GC_MAP.bed file?

Step 1:

A. Process your Hi-C fastq files with HiCPro pipline (https://github.com/nservant/HiC-Pro)

B. Processed HiCPro output directory will have a folder like "<path>/hicresult/bowtie_results/bwt2/data". Under this data folder there will be two *.bwt2merged.bam file (*_1_*.bwt2merged.bam and *_2_*.bwt2merged.bam).

C. "Read_coverage_generation/run_1DReadCoverage.pl" require these two bam files for CNV finding. Change the "$hic_bwt2_folder" variable of "run_1DReadCoverage.pl" script to "<path>/hicresult/bowtie_results/bwt2/data" and type "perl run_1DReadCoverage.pl" inside "Read_coverage_generation" directory. This will create a "1DReadCoverage.*.sh" file.

D. "1DReadCoverage.*.sh" will require a restriction fragment specific *.fragments.F_GC_MAP.bed file(Fragment length, GC content and Mappability information file). To generate this file as per your experiment, please go to "scripts/F_GC_MAP_Files/" directory and type "perl create_F_GC_MAP_file.pl". Change the variables of the script to match your requirement. 

E. Running "1DReadCoverage.*.sh" will create the *.perREfragStats and *.F_GC_MAP.bed files from Hi-C data for downstream processing.
__________________________________________________________________

**Comment by jstansfield0** [comment]
Yes, I ran the 1DReadCoverage.sh script and generated the *.perREfragStats and *.F_GC_MAP.bed files.

**Comment by abhijitcbio** [comment]
Great, please run the next step 

Step2:

A. Copy the *.perREfragStats and *.F_GC_MAP.bed files from "Read_coverage_generation" directory to "CNV_calling" directory.

B. Run "run_HiCnv.pl" script to call CNVs from Hi-C data. 

Check the parameters in the pl script to adjust as per your data.
